### PR TITLE
Release/v0.2.0

### PR DESCRIPTION
**Pull request by Dayjo**
Contains the following features and updates; 

Improve accessibility #8 by @adamsilverstein

Update chars.json key/value data #6 by @jeffpaul

Feature: character search/filter #5 by @adamsilverstein 

Feature: enable overridable character map #3 by @adamsilverstein  

Thank you both or your contributions! :) 

There were a few minor conflicts @adamsilverstein between the search and the refactor of `Chars` / `characters` if you'd like to check I've not missed one that'd be cool. I had to re-implement your readme changes too. I'll merge this is in and release the new version to npm asap

### CODE REVIEW

**Comment by adamsilverstein** [comment]
Super, thanks! I'll take a look and test this out.

**Comment by adamsilverstein** [comment]
In https://github.com/Dayjo/react-character-map/pull/10/commits/5e61c32412ef5fb07346f78f2c62a7105c2b5693 I fixed an issue where the tab changig broke :) When I moved the construction method to componentDidMount, I didn't realize its structure included the active tab and that tab's characters. After this commit, the structure is recalculated whenever the tab changes (as expected).

**Comment by adamsilverstein** [comment]
@Dayjo I noticed when installing the `0.1.10` from npm, the `dist` folder was missing. 

The issue is npm is ignoring the `dist` folder bevause its in `.gitignore`. To fix you can either remove `dist` from the `.gitignore` and commit the `dist` folder, or you can create an empty `.npmignore` file to override using the git ignore file - see https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

One advantage of committing the dist folder is that users can check out the repo and use as is without building. One disadvantage is the continual merge configs the dist files create - because they tend to be single line files, any change will result in a conflict. For this reason I suggest adding an empty `.npmignore` file before publishing.

**Comment by Dayjo** [comment]
@adamsilverstein Thanks for the review. I have merged in your fix. 

Just to clarify your suggestion on ignore files. I've committed the dist directory and added it to `.gitattributes` to attempt to prevent conflicts. The existing .npmignore file should be ok.

**Pull request merged**
