### PR TITLE
Feature: enable overridable character map

### PR DESCRIPTION
**Pull request by adamsilverstein**
## Description
* Enable passing a `characterData` prop to the `CharacterMap` component to override the default data for the tabs and characters to display.

## Use case
The huge number of characters in the character map are fantastic, however some sites may really only want a smaller (or much smaller) set of tabs and characters to be available. 

## Example use
```
import myCharacterData from './chars.json';

<CharacterMap characterData={ myCharacterData }/>
```

### CODE REVIEW

**Comment by Dayjo** [comment]
@adamsilverstein Great idea! If you could add a small update to the readme too I'll get this merged in :)

**Comment by adamsilverstein** [comment]
> If you could add a small update to the readme too I'll get this merged in :)

Good idea, I'll work on it.

**Comment by adamsilverstein** [comment]
@Dayjo I took a pass at the `characterData` property in https://github.com/Dayjo/react-character-map/pull/3/commits/db9b48e10152275dcb0ea348494da453451ce8f8

**Comment by Dayjo** [comment]
@adamsilverstein Great, thanks! I'll try and get this merged in and published soon!

**Comment by Dayjo** [comment]
Apologies, I'm currently going through the Apple keyboard replacement service which is going to take up to 10 days to fix so it'll likely have to happen after I get it back :)

**Comment by adamsilverstein** [comment]
@Dayjo No worries, and thanks for the update. 

I had to have my keyboard replaced as well via mail and Apple got it back to me in an amazing three days, so wishing you expedited service as well!

**Pull request merged**
