### PR TITLE
add games - chess, domino, mahjong, cards and emoji symbols

### PR DESCRIPTION
**Pull request by Sidsector9**
This PR adds the following:

- Games
  - Chess
  - Mahjong
  - Domino
  - Playing Cards
- Emoji symbol

### CODE REVIEW

**Comment by jeffpaul** [comment]
@Dayjo any additional changes you'd want to any of these additional sets before merging & releasing?

**Comment by Dayjo** [comment]
Nope looks great! 👍  Let me know when ready to publish

**Review by Dayjo — APPROVED** [review]

**Comment by jeffpaul** [comment]
@Dayjo no other incoming changes from our end, so good to publish when you are

**Comment by Dayjo** [comment]
Great, are you guys able to set up the tags and releases? I can do `npm publish` whenever you need

**Comment by Sidsector9** [comment]
I've added a minor fix for a prop name in [0195483](https://github.com/Dayjo/react-character-map/pull/54/commits/0195483c3f608299544f65491bb8c53a8e2ee605) to be consistent with the rest of the package.

**Comment by jeffpaul** [comment]
@Dayjo should be good to do `npm publish` now that https://github.com/Dayjo/react-character-map/releases/tag/v0.4.9 is out.  This might be something we can automate via repo settings here in GitHub, so let me know if you'd like me to look into automating that for us... thanks!

**Comment by jeffpaul** [comment]
@Dayjo looks like we could automate the npm publishing via https://github.com/marketplace/actions/npm-publish so that post-GitHub release creation the action would publish to npm.  If you're good with that, mind adding the `NPM_TOKEN` secret to this repo with your NPM auth token and we can set up this action to use with the next release?

**Comment by Dayjo** [comment]
Absolutely 👍

**Pull request merged**
